### ISSUE TITLE
xmrig-proxy support

### ISSUE THREAD

**Issue by Johnson-W** [dunklesToast/XMRigFrontend#8]
Hello,

I found the rig's type have a XMRig Proxy,but no data after configed with the xmrig-proxy API.
Will the XMRigFrontend support xmrig-proxy later?

**Comment by Johnson-W** [comment]
The chrome console display:

DOMException: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.5/angular.min.js:108:10
    at q (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.5/angular.min.js:104:250)
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.5/angular.min.js:102:8
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.5/angular.min.js:136:167
    at m.$digest (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.5/angular.min.js:147:70)
    at m.$apply (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.5/angular.min.js:150:281)
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.5/angular.min.js:22:117
    at Object.invoke (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.5/angular.min.js:44:357)
    at c (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.5/angular.min.js:22:38)
    at Uc (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.5/angular.min.js:22:332) "Possibly unhandled rejection: {"stack":"Error: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL\n    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.5/angular.min.js:108:10\n    at q (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.5/angular.min.js:104:250)\n    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.5/angular.min.js:102:8\n    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.5/angular.min.js:136:167\n    at m.$digest (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.5/angular.min.js:147:70)\n    at m.$apply (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.5/angular.min.js:150:281)\n    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.5/angular.min.js:22:117\n    at Object.invoke (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.5/angular.min.js:44:357)\n    at c (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.5/angular.min.js:22:38)\n    at Uc (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.5/angular.min.js:22:332)"}"

**Comment by dunklesToast** [comment]
Invalid URL means that you have entered a wrong URL for the Rig. Could you please send me the URL?
It should look like: `http://<ip>`

**Comment by dunklesToast** [comment]
Closing due to inactivity
